[package]
name = "browser-esm-webpack"
version = "0.1.0"
authors = ["Shane Osbourne <shane.osbourne8@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="0.2"
rjs = { path = "/Users/shakyshane/sites/oss/bs-rust/rjs-parse" }
